version: "2"
services:
  plex:
    image: linuxserver/plex:latest
    ports:
      - "80:80"
      - "443:443"
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "1900:1900/udp"
    volumes:
      - /mnt/:/mnt/

  sabnzb:
      image: linuxserver/sabnzbd:latest
      ports:
        - "8080:8080"
      volumes:
        - /mnt/:/mnt/
  sonarr:
      image: linuxserver/sonarr:latest
      ports:
        - "8989:8989"
      volumes:
        - /etc/localtime/:/etc/localtime/:ro
        - ./config/sonarr/:/config/:rw
        - /dev/rtc:/dev/rtc:ro
        - /mnt/:/mnt/
      environment:
        - PGID=1000
        - PUID=1000
      depends_on:
        - sabnzb

  couchpotato:
      image: linuxserver/couchpotato:latest
      ports:
        - "5050:5050"
      volumes:
        - /mnt/:/mnt/
      environment:
        - PGID=1000
        - PUID=1000
  headphones:
      image: linuxserver/headphones:latest
      ports:
        - "8181:8181"
      volumes:
        - /mnt/:/mnt/
      environment:
        - PGID=1000
        - PUID=1000
  ombi:
      image: linuxserver/ombi:latest
      ports:
        - "3579:3579"
      volumes:
        - /mnt/:/mnt/
      environment:
        - PGID=1000
        - PUID=1000

  nzbget:
      image: linuxserver/nzbget:latest
      ports:
        - "6789:6789"
      volumes:
        - /mnt/:/mnt/  
      environment:
        - PGID=1000
        - PUID=1000
